

services:
  postgresql:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=shareDocs
    ports:
      - 5432:5432
    networks:
      default:
        ipv4_address: 172.28.0.3
  backend:
    image: sharedocs-backend
    ports:
      - 80:80
    links:
      - postgresql
    networks:
      default:
        ipv4_address: 172.28.0.2

networks:
  default:
    # Use a custom driver
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16