

services:
  postgresql:
    image: postgres:15.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=shareDocs
  backend:
    image: sharedocs-backend
    ports:
      - 80:80
      - 5432:5432
    depends_on:
      - postgresql