services:
  postgresql:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=shareDocs
    ports:
      - 5432:5432
    networks:
      default:
        ipv4_address: 172.28.0.3
    volumes:
      - /var/lib/postgresql/16/main/:/var/lib/postgresql/data/

  backend:
    image: sharedocs-backend
    ports:
      - 127.0.0.1:80:80
    links:
      - postgresql
    networks:
      default:
        ipv4_address: 172.28.0.2

networks:
  default:
    driver: bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/24
