//
// Created by sliderer on 21.11.23.
//

#ifndef SHAREDDOCS_BACK_DATABASECONTROLLER_H
#define SHAREDDOCS_BACK_DATABASECONTROLLER_H


class DatabaseController {

};


#endif //SHAREDDOCS_BACK_DATABASECONTROLLER_H
