//
// Created by sliderer on 21.11.23.
//

#ifndef SHAREDDOCS_BACK_DATABASECONNECTION_H
#define SHAREDDOCS_BACK_DATABASECONNECTION_H


class DatabaseConnection {

};


#endif //SHAREDDOCS_BACK_DATABASECONNECTION_H
